//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDate")]
public interface IDate
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDate/GetCurrentDate", ReplyAction="http://tempuri.org/IDate/GetCurrentDateResponse")]
    string GetCurrentDate();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDate/GetCurrentDate", ReplyAction="http://tempuri.org/IDate/GetCurrentDateResponse")]
    System.Threading.Tasks.Task<string> GetCurrentDateAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDateChannel : IDate, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DateClient : System.ServiceModel.ClientBase<IDate>, IDate
{
    
    public DateClient()
    {
    }
    
    public DateClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DateClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetCurrentDate()
    {
        return base.Channel.GetCurrentDate();
    }
    
    public System.Threading.Tasks.Task<string> GetCurrentDateAsync()
    {
        return base.Channel.GetCurrentDateAsync();
    }
}
